[tool.poetry]
name = "api-testing"
version = "0.1.0"
description = ""
<<<<<<< HEAD
authors = ["Soji Raju <you@example.com>"]
=======
authors = ["Soji Raju <soji.raju@edstem.com>"]
>>>>>>> 6911a21 (soji|api testing)
readme = "README.md"
packages = [{include = "api_testing"}]

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^7.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
